server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8003
  connection-timeout: 5000ms

spring:
  application:
    name: case03-read-write
#  profiles:
#    active: dev

#mybatis-plus:
#  mapper-locations: classpath*:/mapper/**/*.xml
#  typeAliasesPackage: com.dynamic.add.*.entity
#  global-config:
#    db-config:
#      id-type: AUTO
#      field-strategy: NOT_NULL
#      logic-delete-value: -1
#      logic-not-delete-value: 0