server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8004
  connection-timeout: 5000ms

spring:
  application:
    name: case04-shard-ing
  profiles:
    active: dev

mybatis:
  mapper-locations: classpath:/mapper/*.xml