server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8010
  connection-timeout: 5000ms

spring:
  application:
    name: case10-cassand-cluster
  profiles:
    active: test
