spring:
  # Redis配置
  redis:
    host: 127.0.0.1
    timeout: 3000ms
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
  # KafKa配置
  kafka:
    bootstrap-servers: 192.168.72.130:9092
    consumer:
      group-id: test-consumer-group