server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8009
  connection-timeout: 5000ms

spring:
  application:
    name: case09-esearch-cluster
  profiles:
    active: test
